export const LINKS = {
  ADD_LINK: '@@start/links/ADD_LINK',
  REMOVE_LINK: '@@start/links/REMOVE_LINK',
  RESET_LINKS: '@@start/links/RESET_LINKS',
};

export const SETTINGS = {
  UPDATE_SETTING: '@@start/settings/UPDATE_SETTING',
};

export const CURRENCY = {
  REFRESH_STATE: '@@start/currency/REFRESH_STATE',
  FETCH_CURRENCY: '@@start/currency/FETCH_CURRENCY',
  FETCH_CURRENCY_PENDING: '@@start/currency/FETCH_CURRENCY_PENDING',
  FETCH_CURRENCY_FULFILLED: '@@start/currency/FETCH_CURRENCY_FULFILLED',
  FETCH_CURRENCY_REJECTED: '@@start/currency/FETCH_CURRENCY_REJECTED',
  UPDATE_CURRENCY_SETTING: '@@start/currency/UPDATE_CURRENCY_SETTING',
};

export const THOUGHT = {
  REFRESH_STATE: '@@start/thought/REFRESH_STATE',
  FETCH_THOUGHT: '@@start/thought/FETCH_THOUGHT',
  FETCH_THOUGHT_PENDING: '@@start/thought/FETCH_THOUGHT_PENDING',
  FETCH_THOUGHT_FULFILLED: '@@start/thought/FETCH_THOUGHT_FULFILLED',
  FETCH_THOUGHT_REJECTED: '@@start/thought/FETCH_THOUGHT_REJECTED',
};
